unique_ids:
  assets:
    standard-page.html: MINPR4V72RFOOSEFDKRCUVZWUZF4IWKN
    theme.css: NAN7JPT6DV5G4YTPUZG5EPAQIGDXKDFR
  forms:
    Form1: HI4HEYHIDGR5JNCCWXOZOLT5NSGGEHCB
  modules: {}
  scripts: {}
  server_modules: {}
